##===- lib/Transforms/Hello/Makefile -----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = $(shell $(LLVM_ROOT)/scripts/level-to-llvm-root)/llvm-obj
CFLAGS = -I$(LLVM_ROOT)
CXXFLAGS = -I$(LLVM_ROOT)
LIBRARYNAME = mark-region
LOADABLE_MODULE = 1

include $(LEVEL)/Makefile.common

